src/www/common/models/Rango.php
<?php

namespace common\models;
use backend\components\ActiveRecord;

use Yii;

/**
 * This is the model class for table "rango".
 *
 * @property int $id
 * @property int $tipo_parametro_id
 * @property float $desde
 * @property float $hasta
 *
 * @property ParametroRango[] $parametroRangos
 * @property TipoParametro $tipoParametro
 */
class Rango extends ActiveRecord
{
  public static function tableName()
  {
    return 'rango';
  }

  public function rules()
  {
    return [
      [['tipo_parametro_id'], 'required'],
      [['tipo_parametro_id'], 'default', 'value' => null],
      [['tipo_parametro_id'], 'integer'],
      [['nombre'], 'string', 'max' => 64],
      [['texto'], 'string'],
      [['desde', 'hasta'], 'number'],
      [['desde'], 'number', 'min' => 0],
      [['hasta'], 'number', 'max' => 100],
      [['tipo_parametro_id'], 'exist', 'skipOnError' => true,
        'targetClass' => TipoParametro::class,
        'targetAttribute' => ['tipo_parametro_id' => 'id']],
      [['desde'], 'validar'],
    ];
  }


  public function validar()
  {
    if ($this->hasta <= $this->desde) {
      $this->addError('hasta', "Debe ser mayor a $this->desde.");
    }
  }

  public function getNombreRango()
  {
    $desde = $this->desde + 0;
    $hasta = $this->hasta + 0;
    return $this->nombre ?: "$desde% a $hasta%";
  }

  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'tipo_parametro_id' => 'Tipo Parametro ID',
      'desde' => 'Desde',
      'hasta' => 'Hasta',
      'texto' => 'Texto para resultado general',
    ];
  }

  public function attributeHints()
  {
    return [
      'nombre' => 'Alto, medio, bajo, suficiente, insuficiente..',
    ];
  }

  public function afterSave($insert, $changedAttributes)
  {
    $this->revisarRangosParametro();
    parent::afterSave($insert, $changedAttributes);
  }

  public function revisarRangosParametro()
  {
    foreach ($this->tipoParametro->parametros as $parametro) {
      if (!ParametroRango::find()->where([
        'rango_id' => $this->id,
        'parametro_id' => $parametro->id,
      ])->exists()) {
        $parametroRango = new ParametroRango();
        $parametroRango->rango_id = $this->id;
        $parametroRango->parametro_id = $parametro->id;
        $parametroRango->save();
      }
    }
  }

  public function getParametroRangos($parametro_id = null)
  {
    return $this->hasMany(ParametroRango::class, ['rango_id' => 'id']);
  }

  public function getTipoParametro()
  {
    return $this->hasOne(TipoParametro::class, ['id' => 'tipo_parametro_id']);
  }
}

src/www/backend/controllers/RangoController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Rango;
use yii\data\ActiveDataProvider;
use backend\components\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * RangoController implements the CRUD actions for Rango model.
 */
class RangoController extends Controller
{
  public function behaviors()
  {
    return array_merge(parent::behaviors(),
      [
        'verbs' => [
          'class' => VerbFilter::class,
          'actions' => [
            'delete' => ['POST'],
          ],
        ],
      ]
    );
  }

  /**
   * Lists all Rango models.
   *
   * @return string
   */
  public function actionLista()
  {
    $dataProvider = new ActiveDataProvider([
      'query' => Rango::find(),
    ]);
    return $this->render('lista', [
      'dataProvider' => $dataProvider,
    ]);
  }

  /**
   * Displays a single Rango model.
   * @param int $id ID
   * @return string
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionVer($id)
  {
    return $this->render('ver', [
      'model' => $this->findModel($id),
    ]);
  }

  /**
   * Creates a new Rango model.
   * If creation is successful, the browser will be redirected to the 'view' page.
   * @return string|\yii\web\Response
   */
  public function actionAgregar($tipo_parametro_id)
  {
    $model = new Rango();
    $model->tipo_parametro_id = $tipo_parametro_id;

    if ($this->request->isPost) {
      if ($model->load($this->request->post()) && $model->save()) {
        return $this->redirect(Yii::$app->request->get('to', ['ver', 'id' => $model->id]));
      }
    } else {
      $model->loadDefaultValues();
    }
    return $this->render('agregar', [
      'model' => $model,
    ]);
  }

  /**
   * Updates an existing Rango model.
   * If update is successful, the browser will be redirected to the 'ver' page.
   * @param int $id ID
   * @return string|\yii\web\Response
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionEditar($id)
  {
    $model = $this->findModel($id);
    if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
      return $this->redirect(Yii::$app->request->get('to', ['ver', 'id' => $model->id]));
    }
    return $this->render('editar', [
      'model' => $model,
    ]);
  }

  /**
   * Deletes an existing Rango model.
   * If deletion is successful, the browser will be redirected to the 'index' page.
   * @param int $id ID
   * @return \yii\web\Response
   * @throws NotFoundHttpException if the model cannot be found
   */
  public function actionEliminar($id)
  {
    $this->findModel($id)->delete();
    return $this->redirect(Yii::$app->request->get('to', ['lista']));
  }

  /**
   * Finds the Rango model based on its primary key value.
   * If the model is not found, a 404 HTTP exception will be thrown.
   * @param int $id ID
   * @return Rango the loaded model
   * @throws NotFoundHttpException if the model cannot be found
   */
  protected function findModel($id)
  {
    if (($model = Rango::findOne(['id' => $id])) !== null) {
      return $model;
    }
    throw new NotFoundHttpException('The requested page does not exist.');
  }
}

src/www/backend/views/rango/_detalles.php
<div class="ficha rango" data-id="<?= $model->id ?>">

  <main>
  </main>

</div>

src/www/backend/views/rango/_ficha.php
<?php
$opciones = $opciones ?? [];
?>

<div class="ficha rango" data-id="<?= $model->id ?>">

  <header>
    <div class="principal">
      <div class="icono"> <span class="mdi mdi-arrow-expand-horizontal"></span> </div>
      <div class="titulo">
        <div class="nombre">
        <?= $model->id; ?>
        <div class="descripcion">
        </div>
      </div>
    </div>
  </header>

  <main>
    <div class="fila">
      <div class="campo">
        <div class="label"> <?= $model->getAttributeLabel('tipo_parametro_id') ?> </div>
        <div class="value"> <?= $model->tipo_parametro_id ?> </div>
      </div>
    </div>
    <div class="fila">
      <div class="campo">
        <div class="label"> <?= $model->getAttributeLabel('desde') ?> </div>
        <div class="value"> <?= $model->desde ?> </div>
      </div>
    </div>
    <div class="fila">
      <div class="campo">
        <div class="label"> <?= $model->getAttributeLabel('hasta') ?> </div>
        <div class="value"> <?= $model->hasta ?> </div>
      </div>
    </div>
  </main>

</div>

src/www/backend/views/rango/_fields.php
<?php

$attributes = $attributes ?? array_keys($model->attributes);

if ($model->tipoParametro->puntaje_maximo == 0) {
  $model->hasta = 100;
}

?>

<div class="filas">

  <div class="fila">
    <div class="campo nombre grande">
      <i class="mdi mdi-text-box"></i>
      <?= $form->field($model, 'nombre'); ?>
    </div>
  </div>

  <div class="fila completa">
    <div class="campo desde">
      <i class="mdi mdi-arrow-expand-horizontal"></i>
      <?= $form->field($model, 'desde')->number(['step' => 0.1,
        'readonly' => !$model->tipoParametro->getRangos()->exists(),
      ]); ?>
    </div>
    <div class="campo hasta">
      <?= $form->field($model, 'hasta')->number(['step' => 0.1,
        'readonly' => $model->tipoParametro->puntaje_maximo == 0,
      ]); ?>
    </div>
  </div>

  <div class="fila completa">
    <div class="campo texto">
      <i class="mdi mdi-text-long"></i>
      <?= $form->field($model, 'texto')->quillEditor(); ?>
    </div>
  </div>

</div>

src/www/backend/views/rango/_form.php
<?php
use common\widgets\ActiveForm;
use yii\helpers\Url;

$attributes = $attributes ?? array_keys($model->attributes);
?>

<div class="form rango">

  <?php $form = ActiveForm::begin(); ?>

  <?= $this->render('_fields', [
    'form' => $form,
    'model' => $model,
    'attributes' => $attributes,
  ]) ?>

  <div class="opciones">
    <div class="opcion">
      <button class="btn">
        <span class="mdi mdi-<?= $model->isNewRecord ? 'plus-thick' : 'pencil' ?>"></span>
        <?= $model->isNewRecord ? 'Agregar' : 'Guardar' ?>
      </button>
    </div>
    <div class="opcion">
      <a href="<?= Yii::$app->request->get('from', Url::to(['/rango'])) ?>" class="btn-flat solo">
        Cancelar
      </a>
    </div>
  </div>

  <?php ActiveForm::end(); ?>

</div>

src/www/backend/views/rango/_lista.php
<?php
use yii\helpers\Url;
?>

<div class="item" data-id="<?= $model->id ?>">
  <div class="informacion">
    <div class="texto">
      <div class="primario">
        <div class="campo">
          <a href="<?= Url::to(['/rango/ver',
            'id' => $model->id,
            'from' => Url::current()]) ?>">
            <?= $model->id ?>
          </a>
        </div>
      </div>
      <div class="secundario">
      </div>
    </div>
  </div>
  <div class="opciones">
    <div class="opcion hidden">
      <a href="<?= Url::to(['/rango/editar',
        'id' => $model->id,
        'from' => Url::current(),
        'to' => Url::current()]) ?>">
        <span class="mdi mdi-pencil"></span>
      </a>
    </div>
    <div class="opcion hidden">
      <a href="<?= Url::to(['/rango/eliminar',
        'id' => $model->id,
        'to' => Url::current()]) ?>">
        <span class="mdi mdi-delete"></span>
      </a>
    </div>
  </div>
</div>

src/www/backend/views/rango/agregar.php
<?php

$this->title = 'Agregar Rango';
$this->params['icono'] = 'arrow-expand-horizontal';
$this->params['links'] = [
  ['label' => $model->tipoParametro->nombre, 'url' => $model->tipoParametro->url],
  'Agregar rango de resultados',
];

$this->params['cuestionario'] = $model->tipoParametro->cuestionario;
$this->params['menu'] = 'configuracion';

$model->desde = $model->desde ?: $model->tipoParametro->getRangos()->max('hasta') + 0;
$model->hasta = $model->hasta ?: $model->desde;

?>

<div class="rango agregar">

  <?= $this->render('_form', [
    'model' => $model,
    'attributes' => [
      'id',
      'tipo_parametro_id',
      'desde',
      'hasta',
    ],
  ]); ?>

</div>

src/www/backend/views/rango/editar.php
<?php

$this->title = 'Editar ' . $model->id;
$this->params['icono'] = 'arrow-expand-horizontal';
$this->params['links'] = [
  ['label' => 'Rango', 'url' => ['/rango']],
  ['label' => $model->id, 'url' => $model->url],
  'Editar',
];
$this->params['cuestionario'] = $model->tipoParametro->cuestionario;
$this->params['menu'] = 'configuracion';

$model->desde = $model->desde + 0;
$model->hasta = $model->hasta + 0;

?>

<div class="rango editar">

  <?= $this->render('_form', [
    'model' => $model,
    'attributes' => [
      'id',
      'tipo_parametro_id',
      'desde',
      'hasta',
    ],
  ]); ?>

</div>

src/www/backend/views/rango/lista.php
<?php
use common\models\Rango;
use backend\widgets\ListView;
use common\helpers\Html;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;

$this->title = 'Rangos';
$this->params['icono'] = 'arrow-expand-horizontal';
$this->params['links'] = [ 'Rangos'];
$this->params['opciones'][] = Html::a(
  '<span class="mdi mdi-plus"></span> Agregar',
  ['/rango/agregar', 'from' => Url::current(), 'to' => Url::current()],
  [ 'class' => 'btn'],
);
?>

<div class="rango indice">

  <div class="ficha lista">
    <main>
      <?= ListView::widget([
        'dataProvider' => new ActiveDataProvider([
          'query' => Rango::find(),
          'sort' => ['attributes' => ['id']],
          'pagination' => ['pageSize' => 10],
        ]),
        'itemView' => '_lista',
      ]); ?>
    </main>
  </div>

</div>

src/www/backend/views/rango/ver.php
<?php

use common\helpers\Html;
use yii\helpers\Url;

$this->title = $model->nombre;
$this->params['icono'] = 'arrow-expand-horizontal';
$this->params['links'] = [
  ['label' => 'Rango', 'url' => ['/rango']],
  $this->title,
];

$this->params['opciones'][] = Html::a(
    '<span class="mdi mdi-delete"></span> Eliminar',
    ['/rango/eliminar', 'id' => $model->id, 'from' => Url::current()],
    ['class' => 'btn-flat', 'data' => ['confirm' => '¿Está seguro?']]);
$this->params['opciones'][] = Html::a(
    '<span class="mdi mdi-pencil"></span> Editar',
    ['/rango/editar', 'id' => $model->id, 'from' => Url::current(), 'to' => Url::current()],
    ['class' => 'btn']);

$this->params['lateral'] = $this->render('_detalles', ['model'=> $model]);

?>

<div class="rango ver">

  <?= $this->render('_ficha', ['model' => $model]); ?>

</div>