src/www/common/models/Seccion.php
<?php

namespace common\models;
use backend\components\ActiveRecord;
use common\behaviors\FechaBehavior;
use Yii;
use yii\helpers\Url;

/**
 * This is the model class for table "seccion".
 *
 * @property int $id
 * @property int $cuestionario_id
 * @property int $orden
 * @property string|null $nombre
 * @property string|null $descripcion
 * @property string $fecha_creacion
 * @property string|null $fecha_edicion
 */
class Seccion extends ActiveRecord
{

  public function behaviors()
  {
    return [
      FechaBehavior::class,
    ];
  }

  public static function tableName()
  {
    return 'seccion';
  }

  public function rules()
  {
    return [
      [['cuestionario_id', 'nombre'], 'required'],
      [['cuestionario_id', 'orden'], 'default', 'value' => 1],
      [['cuestionario_id', 'orden'], 'integer'],
      [['nombre', 'descripcion'], 'string'],
      [['fecha_creacion', 'fecha_edicion'], 'safe'],
    ];
  }

  public function attributeLabels()
  {
    return [
      'id' => 'ID',
      'cuestionario_id' => 'Cuestionario ID',
      'orden' => 'Orden',
      'nombre' => 'Nombre',
      'descripcion' => 'Descripción',
      'fecha_creacion' => 'Fecha de creación',
      'fecha_edicion' => 'Fecha de edición',
    ];
  }

  public function getUrl() {
    return Url::to(['/cuestionario/preguntas',
      'id' => $this->cuestionario_id,
      '#' => "seccion-$this->id"]);
  }

  public function beforeSave($insert)
  {
    if ($insert) {
      $this->orden = Seccion::find()
        ->where(['cuestionario_id' => $this->cuestionario_id])
        ->max('orden') + 1;
    }
    if ($this->isAttributeChanged('orden')) {
      $this->ordenar();
    }
    return parent::beforeSave($insert);
  }

  private function ordenar()
  {
    if ($this->cuestionario->getSecciones()->andWhere(['orden' => $this->orden])->exists()) {
      $orden = $this->orden;
      if ($orden == 1 || $this->oldAttributes['orden'] > $this->orden) {
        foreach ($this->cuestionario->getSecciones()->andWhere(['AND',
          ['<>', 'id', $this->id],
          ['>=', 'orden', $this->orden],
        ])->orderBy('orden ASC')->all() as $i => $seccion) {
          $seccion->updateAttributes(['orden' => $orden + $i + 1]);
        }
      } else {
        foreach ($this->cuestionario->getSecciones()->andWhere(['AND',
          ['<>', 'id', $this->id],
          ['<=', 'orden', $this->orden],
        ])->orderBy('orden DESC')->all() as $i => $seccion) {
          $seccion->updateAttributes(['orden' => $orden - $i - 1]);
        }
      }
    }
  }

  public function beforeDelete()
  {
    return parent::beforeDelete();
  }

  public function afterSave($insert, $changedAttributes)
  {
    parent::afterSave($insert, $changedAttributes);
  }

  public function getCuestionario()
  {
    return $this->hasOne(Cuestionario::class, ['id' => 'cuestionario_id']);
  }

  public function getPreguntas()
  {
    return $this->hasMany(Pregunta::class, ['seccion_id' => 'id']);
  }

  function renumerarPreguntas()
  {
    foreach ($this->getPreguntas()->orderBy('orden')->all() as $orden => $etiqueta) {
      $etiqueta->updateAttributes(['orden' => $orden + 1]);
    }
  }
}

src/www/backend/controllers/SeccionController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Seccion;
use yii\data\ActiveDataProvider;
use backend\components\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

class SeccionController extends Controller
{
  public function behaviors()
  {
    return array_merge(parent::behaviors(),
      [
        'verbs' => [
          'class' => VerbFilter::class,
          'actions' => [
            'delete' => ['POST'],
          ],
        ],
      ]
    );
  }

  public function actionLista()
  {
    $dataProvider = new ActiveDataProvider([
      'query' => Seccion::find(),
    ]);
    return $this->render('lista', [
      'dataProvider' => $dataProvider,
    ]);
  }

  public function actionVer($id)
  {
    return $this->render('ver', [
      'model' => $this->findModel($id),
    ]);
  }

  public function actionOrdenar($id, $orden = 1)
  {
    $model = Seccion::findOne($id);
    $model->orden = $orden;
    $model->save();
    return $this->redirect(['/cuestionario/preguntas', 'id' => $model->cuestionario_id]);
  }

  public function actionAgregar($cuestionario_id)
  {
    $model = new Seccion();
    $model->cuestionario_id = $cuestionario_id;

    if ($this->request->isPost) {
      if ($model->load($this->request->post()) && $model->save()) {
        return $this->redirect(Yii::$app->request->get('to', ['ver', 'id' => $model->id]));
      }
    } else {
      $model->loadDefaultValues();
    }
    return $this->render('agregar', [
      'model' => $model,
    ]);
  }

  public function actionEditar($id)
  {
    $model = $this->findModel($id);
    if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
      return $this->redirect(Yii::$app->request->get('to', ['ver', 'id' => $model->id]));
    }
    return $this->render('editar', [
      'model' => $model,
    ]);
  }

  public function actionEliminar($id)
  {
    $this->findModel($id)->delete();
    return $this->redirect(Yii::$app->request->get('to', ['lista']));
  }

  protected function findModel($id)
  {
    if (($model = Seccion::findOne(['id' => $id])) !== null) {
      return $model;
    }
    throw new NotFoundHttpException('The requested page does not exist.');
  }
}

src/www/backend/views/seccion/_detalles.php
<div class="ficha seccion" data-id="<?= $model->id ?>">

  <main>
    <div class="fila">
      <div class="campo">
        <div class="label">
          <?= $model->getAttributeLabel('fecha_creacion') ?>
        </div>
        <div class="value">
          <?= Yii::$app->formatter->asDatetime($model->fecha_creacion) ?>
        </div>
      </div>
    </div>
    <div class="fila">
      <div class="campo">
        <div class="label">
          <?= $model->getAttributeLabel('fecha_edicion') ?>
        </div>
        <div class="value">
          <?= Yii::$app->formatter->asDatetime($model->fecha_edicion) ?>
        </div>
      </div>
    </div>
  </main>

</div>

src/www/backend/views/seccion/_ficha.php
<?php
$opciones = $opciones ?? [];
?>

<div class="ficha seccion" data-id="<?= $model->id ?>">

  <header>
    <div class="principal">
      <div class="icono"> <span class="mdi mdi-view-agenda"></span> </div>
      <div class="titulo">
        <div class="nombre">
        <?= $model->nombre; ?>
        <div class="descripcion">
        </div>
      </div>
    </div>
  </header>

  <main>
    <div class="fila">
      <div class="campo">
        <div class="label"> <?= $model->getAttributeLabel('cuestionario_id') ?> </div>
        <div class="value"> <?= $model->cuestionario_id ?> </div>
      </div>
    </div>
    <div class="fila">
      <div class="campo">
        <div class="label"> <?= $model->getAttributeLabel('orden') ?> </div>
        <div class="value"> <?= $model->orden ?> </div>
      </div>
    </div>
    <div class="fila">
      <div class="campo">
        <div class="label"> <?= $model->getAttributeLabel('nombre') ?> </div>
        <div class="value"> <?= $model->nombre ?> </div>
      </div>
    </div>
    <div class="fila">
      <div class="campo">
        <div class="label"> <?= $model->getAttributeLabel('descripcion') ?> </div>
        <div class="value"> <?= $model->descripcion ?> </div>
      </div>
    </div>
  </main>

</div>

src/www/backend/views/seccion/_fields.php
<?php
$attributes = $attributes ?? array_keys($model->attributes);
?>

<div class="filas">

  <?php if (in_array('nombre', $attributes)): ?>
  <div class="fila">
    <div class="campo nombre grande">
      <i class="mdi mdi-text-box"></i>
      <?= $form->field($model, 'nombre'); ?>
    </div>
  </div>
  <?php endif; ?>

  <?php if (in_array('descripcion', $attributes)): ?>
  <div class="fila">
    <div class="campo descripcion grande">
      <i class="mdi mdi-text-box"></i>
      <?= $form->field($model, 'descripcion')->quillEditor(); ?>
    </div>
  </div>
  <?php endif; ?>

</div>

src/www/backend/views/seccion/_form.php
<?php
use common\widgets\ActiveForm;
use yii\helpers\Url;

$attributes = $attributes ?? array_keys($model->attributes);
?>

<div class="form seccion">

  <?php $form = ActiveForm::begin(); ?>

  <?= $this->render('_fields', [
    'form' => $form,
    'model' => $model,
    'attributes' => $attributes,
  ]) ?>

  <div class="opciones">
    <div class="opcion">
      <button class="btn">
        <span class="mdi mdi-<?= $model->isNewRecord ? 'plus-thick' : 'pencil' ?>"></span>
        <?= $model->isNewRecord ? 'Agregar' : 'Guardar' ?>
      </button>
    </div>
    <div class="opcion">
      <a href="<?= Yii::$app->request->get('from', Url::to(['/seccion'])) ?>" class="btn-flat solo">
        Cancelar
      </a>
    </div>
  </div>

  <?php ActiveForm::end(); ?>

</div>

src/www/backend/views/seccion/_header.php
<?php

?>

<header>
  <div class="principal">
    <div class="icono"> <span class="mdi mdi-help-box"></span> </div>
    <div class="titulo">
      <div class="nombre">
        <?= $model->nombre; ?>
      </div>
      <div class="descripcion">
      </div>
    </div>
  </div>
</header>

src/www/backend/views/seccion/_indice.php
<?php
use yii\helpers\Url;

$opciones = $opciones ?? [];
?>

<div class="ficha">

  <header>
    <div class="principal">
      <div class="icono"> <span class="mdi mdi-help-box"></span> </div>
      <div class="titulo">
        <div class="nombre">
          <?php if (!isset($link) || $link): ?>
            <a href="<?= Url::to(['/seccion']) ?>">
              Secciones
            </a>
          <?php else: ?>
            Secciones
          <?php endif ?>
        </div>
        <div class="descripcion">
        </div>
      </div>
    </div>

    <?php if ($opciones): ?>
    <div class="opciones">

      <?php if (in_array('agregar', $opciones)): ?>
      <div class="opcion">
        <a href="<?= Url::to(['/seccion/agregar']) ?>" class="btn">
          <span class="mdi mdi-plus-thick"></span> Agregar
        </a>
      </div>
      <?php endif ?>

    </div>
    <?php endif ?>

  </header>

</div>

src/www/backend/views/seccion/_lista.php
<?php
use yii\helpers\Url;
?>

<div class="item" data-id="<?= $model->id ?>">
  <div class="informacion">
    <div class="texto">
      <div class="primario">
        <div class="campo">
          <a href="<?= Url::to(['/seccion/ver',
            'id' => $model->id,
            'from' => Url::current()]) ?>">
            <?= $model->nombre ?>
          </a>
        </div>
      </div>
      <div class="secundario">
      </div>
    </div>
  </div>
  <div class="opciones">
    <div class="opcion hidden">
      <a href="<?= Url::to(['/seccion/editar',
        'id' => $model->id,
        'from' => Url::current(),
        'to' => Url::current()]) ?>">
        <span class="mdi mdi-pencil"></span>
      </a>
    </div>
    <div class="opcion hidden">
      <a href="<?= Url::to(['/seccion/eliminar',
        'id' => $model->id,
        'to' => Url::current()]) ?>">
        <span class="mdi mdi-delete"></span>
      </a>
    </div>
  </div>
</div>

src/www/backend/views/seccion/agregar.php
<?php

$this->title = 'Agregar Seccion';

$this->params['cuestionario'] = $model->cuestionario;
$this->params['menu'] = 'preguntas';

$this->params['icono'] = 'view-agenda';
$this->params['links'] = [
  ['label' => $model->cuestionario->nombre, 'url' => $model->cuestionario->url],
  'Agregar sección',
];

?>

<div class="seccion agregar">

  <?= $this->render('_form', [
    'model' => $model,
    'attributes' => [
      'id',
      'cuestionario_id',
      'orden',
      'nombre',
      'descripcion',
      'fecha_creacion',
      'fecha_edicion',
    ],
  ]); ?>

</div>

src/www/backend/views/seccion/editar.php
<?php

$this->title = 'Editar ' . $model->nombre;

$this->params['cuestionario'] = $model->cuestionario;
$this->params['menu'] = 'preguntas';

$this->params['icono'] = 'view-agenda';
$this->params['links'] = [
  ['label' => $model->nombre, 'url' => $model->url],
  'Editar',
];

?>

<div class="seccion editar">

  <?= $this->render('_form', [
    'model' => $model,
    'attributes' => [
      'id',
      'cuestionario_id',
      'orden',
      'nombre',
      'descripcion',
      'fecha_creacion',
      'fecha_edicion',
    ],
  ]); ?>

</div>

src/www/backend/views/seccion/lista.php
<?php
use common\models\Seccion;
use backend\widgets\ListView;
use common\helpers\Html;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;

$this->title = 'Seccions';
$this->params['icono'] = 'view-agenda';
$this->params['links'] = [ 'Seccions'];
$this->params['opciones'][] = Html::a(
  '<span class="mdi mdi-plus"></span> Agregar',
  ['/seccion/agregar', 'from' => Url::current(), 'to' => Url::current()],
  [ 'class' => 'btn'],
);
?>

<div class="seccion indice">

  <div class="ficha lista">
    <main>
      <?= ListView::widget([
        'dataProvider' => new ActiveDataProvider([
          'query' => Seccion::find(),
          'sort' => ['attributes' => ['nombre']],
          'pagination' => ['pageSize' => 10],
        ]),
        'itemView' => '_lista',
      ]); ?>
    </main>
  </div>

</div>

src/www/backend/views/seccion/ver.php
<?php

use common\helpers\Html;
use yii\helpers\Url;

$this->title = $model->nombre;
$this->params['icono'] = 'view-agenda';
$this->params['links'] = [
  ['label' => 'Seccion', 'url' => ['/seccion']],
  $this->title,
];

$this->params['opciones'][] = Html::a(
    '<span class="mdi mdi-delete"></span> Eliminar',
    ['/seccion/eliminar', 'id' => $model->id, 'from' => Url::current()],
    ['class' => 'btn-flat', 'data' => ['confirm' => '¿Está seguro?']]);
$this->params['opciones'][] = Html::a(
    '<span class="mdi mdi-pencil"></span> Editar',
    ['/seccion/editar', 'id' => $model->id, 'from' => Url::current(), 'to' => Url::current()],
    ['class' => 'btn']);
$this->params['lateral'] = $this->render('_detalles', ['model'=> $model]);
?>

<div class="seccion ver">

  <?= $this->render('_ficha', ['model' => $model]); ?>

</div>